In [1]:
%matplotlib inline
import numpy as np

In [2]:
sensor_num = 17
train = [open("C:/Users/skywayoo/FDC/benchmark/data/sensor_cv/train_1/cv_1_train_%d.txt" % i) for i in range(1, sensor_num+1)]
test = [open("C:/Users/skywayoo/FDC/benchmark/data/sensor_cv/test_1/cv_1_test_%d.txt" % i) for i in range(1, sensor_num+1)]

In [3]:
def read_Data(txt):
    data = txt.readlines()
    data = [i.split('\n', 1)[0] for i in data]
    readlines = []
    for i in range(0,len(data)):
        readlines.append(data[i].split())
    return np.array(readlines)
train_sensors = []
test_sensors = []
for i in range(0,sensor_num):
    train_sensors.append(read_Data(train[i]))
    test_sensors.append(read_Data(test[i]))
    
#sensor_val[sensor_num][wafer_num]
train_length = np.array(train_sensors).shape[1]
test_length =  np.array(test_sensors).shape[1]
print("train dim=",np.array(train_sensors).shape)
print("test dim=",np.array(test_sensors).shape)

('train dim=', (17L, 150L))
('test dim=', (17L, 39L))


In [5]:
def rstr(data):
    lenval = []
    print('sensor count = ',len(data))
    for i in range(0,len(data)):
        lenval.append(len(data[i]))
    print('MAX=',max(lenval))
    print('MIN=',min(lenval))
    return [np.array(lenval),min(lenval)]

def sensor_label(data):
    label = []
    for i in range(0,len(data[0])):
        label.append(data[0][i][0])
    return np.array(label)

train_label = sensor_label(train_sensors)
test_label = sensor_label(test_sensors)

print("train.y=",train_label,"length=",train_label.shape)
print("test.y=",test_label,"length=",test_label.shape)

('train.y=', array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0'],
      dtype='|S1'), 'length=', (150L,))
('test.y=', array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '

In [6]:
def sensor_value(data):
    for s in range(0,len(data)):
        for i in range(0,len(data[s])):
            data[s][i].pop(0)
    return data
                       
train_sensor_val = sensor_value(train_sensors)
test_sensor_val = sensor_value(test_sensors)

print(np.array(train_sensor_val[0][0][0:20]))
print(np.array(test_sensor_val[0][0][0:20]))

['-1.1' '-1.1' '-1.1' '-1.1' '-1.1' '-1.1'
 '-1.1' '-1.1' '-1.1' '-1.1' '-1.1' '-1.1'
 '-1.1' '-1.1' '-1.1' '-1.1' '-1.1' '-1.1'
 '-1.1' '-1.1']
['-1.1' '-1.1' '-1.1' '-1.1' '-1.1' '-1.1'
 '-1.1' '-1.1' '-1.1' '-1.1' '-1.1' '-1.1'
 '-1.1' '-1.1' '-1.1' '-1.1' '-1.1' '-1.1'
 '-1.1' '-1.1']


In [7]:
np.array(test_sensors[0][0])[0:20] == np.array(test_sensor_val[0][0][0:20])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [8]:
min_len = min(rstr(train_sensor_val[0])[1],rstr(test_sensor_val[0])[1])

('sensor count = ', 150)
('MAX=', 212)
('MIN=', 149)
('sensor count = ', 39)
('MAX=', 212)
('MIN=', 198)


In [9]:
def sliding_win(ts,w_size):
    window = []
    for i in range(0,len(ts)-w_size+1):
        window_v = ts[i:i+w_size]
        window.append(window_v)
    return window

def each_len(data,win_size):
    sliding_len = []
    for i in range(0,len(data[0])):
        sliding_len.append(len(sliding_win(data[0][i],win_size)))
    return np.array(sliding_len)

#slide each length
each_len(train_sensor_val,min_len)

array([56, 56, 58, 55, 55, 58, 51, 56, 57, 55, 55, 56, 54, 50, 56, 56, 57,
       58, 56, 56, 56, 54, 57, 57, 56, 55, 55, 52, 55, 57, 56, 55, 55, 55,
       55, 56, 57, 56, 57, 51, 54, 51, 55, 58, 56, 51, 57, 63, 61, 62, 63,
       62, 63, 62, 62, 63, 64, 56, 55, 62, 63, 63, 56, 62, 62, 57, 56, 55,
       58, 55, 55, 55, 57,  1, 55, 50, 56, 56, 58, 56, 57, 56, 56, 57, 56,
       56, 51, 56, 57, 57, 56, 56, 56, 57, 58, 55, 54, 56, 56, 51, 55, 55,
       56, 50, 51, 56, 55, 57, 56, 56, 55, 52, 55, 51, 57, 51, 57, 51, 56,
       56, 55, 56, 55, 57, 55, 56, 51, 56, 57, 57, 56, 57, 56, 55, 56, 56,
       57, 56, 56, 55, 55, 55, 57, 55, 56, 56, 56, 55, 55, 55])

In [10]:
def wafer_idx(sensor,num_wafer,win_size):
    total = sum(each_len(sensor,win_size))
    val = each_len(sensor,win_size)
    idx = np.array(range(sum(val[0:num_wafer-1]),sum(val[0:num_wafer-1],val[num_wafer-1])))
    return idx

#each wafer after slide "index"!!! for predict label
wafer_idx(train_sensor_val,3,min_len-1)

array([114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172])

In [11]:
sensor_trainX = [sliding_win(train_sensor_val[0][i],min_len) for i in range(0,train_length)]
sensor_testX = [sliding_win(test_sensor_val[0][i],min_len) for i in range(0,test_length)]

In [12]:
print("train=",len(sensor_trainX))
print("test=",len(sensor_testX))

('train=', 150)
('test=', 39)


In [13]:
def unlist(df):
    unlist_val = []
    for i in range(0,len(df)):
        for s in range(0,len(df[i])):
            unlist_val.append(df[i][s])
    return unlist_val

def sensor_X(sensor,sensor_num,win_size):
    sensor_num=sensor_num-1
    sensor_dat = [sliding_win(sensor[sensor_num][i],win_size) for i in range(0, len(sensor[sensor_num]))]
    sensor_dat = np.asarray(unlist(sensor_dat))
    sensor_dat.reshape(sum(each_len(sensor,win_size)),win_size)
    return sensor_dat

In [14]:
print("train:",np.shape(sensor_X(train_sensor_val,1,min_len)))
print("test:",np.shape(sensor_X(test_sensor_val,1,min_len)))

('train:', (8356L, 149L))
('test:', (2179L, 149L))


In [15]:
min_len

149

In [16]:
train_x = []
test_x = []
for i in range(0,17):
    train_x.append(sensor_X(train_sensor_val,i+1,min_len))
    test_x.append(sensor_X(test_sensor_val,i+1,min_len))
    #change type
    train_x[i] = train_x[i].astype(np.float32)
    test_x[i] = test_x[i].astype(np.float32)
    train_x[i] = train_x[i].reshape(np.shape(sensor_X(train_sensor_val,1,min_len))[0],min_len,1)
    test_x[i] = test_x[i].reshape(np.shape(sensor_X(test_sensor_val,1,min_len))[0],min_len,1)

#train
#train_x
#[num_sensor][num_sensor_value(windows)][timeseries_min_value]

In [17]:
len(train_x[0][0])

149

In [18]:
def y_label(data,label,win_size,wafer_num):
    n_label = []
    for i in wafer_num:
        n_label.append(np.repeat(label[i],each_len(data,win_size)[i]).astype('int'))
    return np.array(unlist(n_label))

train_y = y_label(train_sensor_val,train_label,149,range(0,len(train_sensor_val[0])))
test_y = y_label(test_sensor_val,test_label,149,range(0,len(test_sensor_val[0])))
print("test:",len(test_y))
print("train:",len(train_y))

('test:', 2179)
('train:', 8356)
